import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FaCheck } from "react-icons/fa";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://www.dafontfree.net/embed/YW1lcmlnby1idC1yb21hbiZkYXRhLzQ2L2EvNTkxNDQvQW1lcmlnbyBCVC50dGY"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      {/* NAVBAR */}
      <div>NAVBAR</div>

      <main className="!bg-scroll block overflow-hidden w-full">
        <div className="pt-[110px] pb-[40px] !bg-scroll relative">
          <div className="relative z-2 !bg-scroll maxmd:px-[1.25rem] px-10">
            {/* LEFT CONTENT */}
            <div className="!bg-scroll w-full max-w-[70rem] mx-auto">
              <div
                className="pr-0 maxmd:flex-wrap maxlg:mt-0 flex mx-auto w-full mt-[4%]
                justify-between items-center maxlg:top-0 relative max-w-[36rem]"
              >
                <div
                  className="!bg-scroll maxxs:mt-0 maxxs:mx-0 maxmd:mb-5
                maxlg:mt-0 maxlg:mx-0 maxlg:mb-6 mt-0 mx-0 mb-[0.9375rem]"
                >
                  <h1
                    className="font-normal !bg-scroll maxmd:text-2xl my-0
                  text-[2.5rem] leading-[120%] maxxs:leading-[36px]
                  maxmd:text-[28px] maxmd:leading-[42px] font-[amerigo-bt-roman]"
                  >
                    Plans & Pricing
                  </h1>
                </div>
                <div
                  className="!bg-scroll maxxs:mt-[50px] justify-center maxmd:mt-[60px]
                justify-end flex-1 relative flex items-center"
                >
                  <div
                    className="!bg-scroll text-[17px] font-[600] tracking-[1.22px]
                  uppercase"
                  >
                    Monthly
                  </div>
                  <div
                    className="!bg-scroll cursor-pointer touch-manipulation flex
                  w-[50px] h-[29px] mx-[28px] px-0 items-center rounded-[200px]
                  bg-[#0b289]"
                  >
                    <div
                      className="!bg-scroll w-[25px] h-[25px] px-[2px] rounded-[200px]
                    bg-white"
                    ></div>
                  </div>
                  <div
                    className="!bg-scroll relative z-2 opacity-[.65] text-[#4c4d5f]
                  text-[16px] font-[600] tracking-[1.22px] uppercase"
                  >
                    Yearly
                  </div>
                </div>
              </div>
              {/* PRICING MONTHLY */}
              <div className="flex !bg-scroll maxlg:flex-col pt-[40px] justify-between flex-wrap">
                {/* PLAN DIV 1 */}
                <div
                  class="!bg-scroll maxxs:px-[23px] maxxs:pb-[40px] maxlg:w-full maxlg:mb-[30px]
                maxlg:py-[50px] relative flex overflow-hidden w-[32%] py-[6%] px-[4%] flex-col
                border-[0.3px] border-solid border-[rgba(2,4,69, 0.15)] rounded-[4px]
                shadow-[0_0_68_px_0_rgba(2,4,69,8%)]"
                >
                  <div
                    class="!bg-scroll maxmd:text-[1.5rem] font-[600] my-0 text-[1.625rem]
                  leading-[1.4] font-[700]"
                  >
                    Starter
                  </div>
                  <div class="!bg-scroll max-w-[90%]">
                    Ideal for freelancers and contractors just starting out.
                  </div>
                  <div class="!bg-scroll w-full mt-[20px] border-b-[2px] border-b-solid border-b-[#01b289]">
                    <div
                      class="!bg-scroll maxmd:text-[70px] maxmd:leading-[80px] flex items-end text-[62px]
                    leading-[72px] font-[600]"
                    >
                      <span
                        class="!bg-scroll maxxs:text-[28px] leading-[43px] maxmd:leading-[49px]
                      relative top-[10px] mr-[10px] self-start text-[30px] leading-[28px] font-[400]"
                      >
                        $
                      </span>
                      24
                      <span
                        class="!bg-scroll my-0 mr-0 maxmd:text-[1.5rem] maxmd:ml-[1.25rem]
                      maxlg:my-0 maxlg:mr-0 maxlg:ml-[1.5rem] uppercase font-[400] text-[1.625rem]
                      leading-[1.4] font-[700] m-[0.9375rem]"
                      >
                        /month
                      </span>
                    </div>
                  </div>
                  <div class="!bg-scroll mb-[25px] pt-[40px]">
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>All Templates</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Unlimited Clients &amp; Projects</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Invoicing &amp; Payments</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Proposals &amp; Contracts</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Tasks &amp; Time Tracking</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Client CRM</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Expense Tracking</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Up to 5 Project Collaborators</div>
                    </div>
                  </div>
                  <div class="mt-auto !bg-scroll mx-0 ml-0">
                    <a
                      className="!bg-scroll maxmd:text-[15px] w-full py-[22px] px-[25px]
                    rounded-[4px] bg-[#00b289] font-bold text-center tracking-[.7px]
                    no-underline uppercase inline-block border-none cursor-pointer"
                    >
                      Start Free
                    </a>
                  </div>
                </div>
                {/* PLAN DIV 2 */}
                <div
                  class="!bg-scroll maxxs:px-[23px] maxxs:pb-[40px] maxlg:w-full maxlg:mb-[30px]
                maxlg:py-[50px] relative flex overflow-hidden w-[32%] py-[6%] px-[4%] flex-col
                border-[0.3px] border-solid border-[rgba(2,4,69, 0.15)] rounded-[4px]
                shadow-[0_0_68_px_0_rgba(2,4,69,8%)]"
                >
                  <div
                    class="!bg-scroll maxmd:text-[1.5rem] font-[600] my-0 text-[1.625rem]
                  leading-[1.4] font-[700]"
                  >
                    Professionnal
                  </div>
                  <div class="!bg-scroll max-w-[90%]">
                    Everything a growing independent business needs to thrive.{" "}
                  </div>
                  <div class="!bg-scroll w-full mt-[20px] border-b-[2px] border-b-solid border-b-[#01b289]">
                    <div
                      class="!bg-scroll maxmd:text-[70px] maxmd:leading-[80px] flex items-end text-[62px]
                    leading-[72px] font-[600]"
                    >
                      <span
                        class="!bg-scroll maxxs:text-[28px] leading-[43px] maxmd:leading-[49px]
                      relative top-[10px] mr-[10px] self-start text-[30px] leading-[28px] font-[400]"
                      >
                        $
                      </span>
                      39
                      <span
                        class="!bg-scroll my-0 mr-0 maxmd:text-[1.5rem] maxmd:ml-[1.25rem]
                      maxlg:my-0 maxlg:mr-0 maxlg:ml-[1.5rem] uppercase font-[400] text-[1.625rem]
                      leading-[1.4] font-[700] m-[0.9375rem]"
                      >
                        /month
                      </span>
                    </div>
                  </div>
                  <div class="!bg-scroll mb-[25px] pt-[40px]">
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Everything in Starter plus...</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Custom Branding</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Forms & Questionnaires</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Workflow Automations</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Client Portal</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>QuickBooks Integration</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Calendly Integration</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Zapier Integration</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Up to 15 Project Collaborators</div>
                    </div>
                  </div>
                  <div class="mt-auto !bg-scroll mx-0 ml-0">
                    <a
                      className="!bg-scroll maxmd:text-[15px] w-full py-[22px] px-[25px]
                    rounded-[4px] bg-[#00b289] font-bold text-center tracking-[.7px]
                    no-underline uppercase inline-block border-none cursor-pointer"
                    >
                      Start Free
                    </a>
                  </div>
                </div>
                {/* PLAN DIV 3 */}
                <div
                  class="!bg-scroll maxxs:px-[23px] maxxs:pb-[40px] maxlg:w-full maxlg:mb-[30px]
                maxlg:py-[50px] relative flex overflow-hidden w-[32%] py-[6%] px-[4%] flex-col
                border-[0.3px] border-solid border-[rgba(2,4,69, 0.15)] rounded-[4px]
                shadow-[0_0_68_px_0_rgba(2,4,69,8%)]"
                >
                  <div
                    class="!bg-scroll maxmd:text-[1.5rem] font-[600] my-0 text-[1.625rem]
                  leading-[1.4] font-[700]"
                  >
                    Business
                  </div>
                  <div class="!bg-scroll max-w-[90%]">
                    The perfect package for small businesses and agencies.{" "}
                  </div>
                  <div class="!bg-scroll w-full mt-[20px] border-b-[2px] border-b-solid border-b-[#01b289]">
                    <div
                      class="!bg-scroll maxmd:text-[70px] maxmd:leading-[80px] flex items-end text-[62px]
                    leading-[72px] font-[600]"
                    >
                      <span
                        class="!bg-scroll maxxs:text-[28px] leading-[43px] maxmd:leading-[49px]
                      relative top-[10px] mr-[10px] self-start text-[30px] leading-[28px] font-[400]"
                      >
                        $
                      </span>
                      79
                      <span
                        class="!bg-scroll my-0 mr-0 maxmd:text-[1.5rem] maxmd:ml-[1.25rem]
                      maxlg:my-0 maxlg:mr-0 maxlg:ml-[1.5rem] uppercase font-[400] text-[1.625rem]
                      leading-[1.4] font-[700] m-[0.9375rem]"
                      >
                        /month
                      </span>
                    </div>
                  </div>
                  <div class="!bg-scroll mb-[25px] pt-[40px]">
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Everything in Starter and Professional plus...</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Subcontractor Management</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Hiring Agreement Templates (1099 contracts)</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Subcontractor Onboarding</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Talent Pool</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>3 Team Seats (additional seats $9/month)</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Accountant Access</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Connect Multiple Bank Accounts</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Unlimited Subcontractors</div>
                    </div>
                    <div class="!bg-scroll flex pb-[18px] items-center text-[#4c4d5f] text-[16px] leading-[23px]">
                      <FaCheck
                        className="maxxs:my-0 maxxs:ml-0 maxmd:my-0 maxmd:ml-0 maxlg:my-0 maxlg:ml-0
                      my-0 ml-0 mr-[.625rem] text-[#00b289] border-none align-middle inline-block max-w-full
                      w-[12px]"
                      />
                      <div>Unlimited Project Collaborators</div>
                    </div>
                  </div>
                  <div class="mt-auto !bg-scroll mx-0 ml-0">
                    <a
                      className="!bg-scroll maxmd:text-[15px] w-full py-[22px] px-[25px]
                    rounded-[4px] bg-[#00b289] font-bold text-center tracking-[.7px]
                    no-underline uppercase inline-block border-none cursor-pointer"
                    >
                      Start Free
                    </a>
                  </div>
                </div>
                {/* PLAN DIV 4 */}
                <div className="!bg-scroll mx-0 mb-0 maxmd:mt-[4.5rem] w-full max-w-none">
                  <div className="mt-[20px] mb-[40px] !bg-scroll">
                    <h2
                      className="font-normal !bg-scroll maxmd:text-[1.5rem] text-center
                    my-0 leading-[140%] maxmd:text-[24px] maxmd:leading-[36px] mt-[20px]
                    mb-[10px] text-[#4c525a] text-[32px]"
                    >
                      Super charge your work with add-ons
                    </h2>
                  </div>
                  <div
                    className="maxmd:py-[20px] mb-[10px] pt-[10px] px-[40px] pb-[5px]
                  !bg-scroll maxxs:px-[25px] maxmd:flex-col-reverse flex-wrap items-start
                  content-start maxlg:px-[40px] flex justify-between rounded-[8px] bg-[#fff]
                  shadow-[0_0_60px_0_rgb(2,4,69,5)]"
                  >
                    <div></div>
                    <div></div>
                  </div>
                  <div
                    className="maxmd:py-[20px] mb-[10px] pt-[10px] px-[40px] pb-[5px]
                  !bg-scroll maxxs:px-[25px] maxmd:flex-col-reverse flex-wrap items-start
                  content-start maxlg:px-[40px] flex justify-between rounded-[8px] bg-[#fff]
                  shadow-[0_0_60px_0_rgb(2,4,69,5)]"
                  ></div>
                  <div className="addonbox"></div>
                </div>
              </div>
              {/* PRICING YEARLY */}
              <div className="pricing_yearly">YEARLY</div>
            </div>
          </div>
        </div>
      </main>

      <footer>FOOTER</footer>
    </div>
  );
}
