import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://www.dafontfree.net/embed/YW1lcmlnby1idC1yb21hbiZkYXRhLzQ2L2EvNTkxNDQvQW1lcmlnbyBCVC50dGY"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      {/* NAVBAR */}
      <div>NAVBAR</div>

      <main className="!bg-scroll block overflow-hidden w-full">
        <div className="pt-[110px] pb-[40px] !bg-scroll relative">
          <div className="relative z-2 !bg-scroll maxmd:px-[1.25rem] px-10">
            <div className="!bg-scroll w-full max-w-[70rem] mx-auto">
              <div
                className="pr-0 flex-wrap maxlg:mt-0 flex mx-auto w-full mt-[4%]
                justify-between items-center maxlg:top-0 relative max-w-[36rem]"
              >
                <div
                  className="!bg-scroll maxxs:mt-0 maxxs:mx-0 maxmd:mb-5
                maxlg:mt-0 maxlg:mx-0 maxlg:mb-6 mt-0 mx-0 mb-[0.9375rem]"
                >
                  <h1
                    className="font-normal !bg-scroll maxmd:text-2xl my-0
                  text-[2.5rem] leading-[120%] maxxs:leading-[36px]
                  maxmd:text-[28px] maxmd:leading-[42px] font-[amerigo-bt-roman]"
                  >
                    Plans & Pricing
                  </h1>
                </div>
                <div>left2</div>
              </div>
              <div className="pricing_monthly">MONTHLY</div>
              <div className="pricing_yearly">YEARLY</div>
            </div>
          </div>
        </div>
      </main>

      <footer>FOOTER</footer>
    </div>
  );
}
